meridian_dbt:
  outputs:
    dev:
      type: postgres
      host: aws-0-us-west-2.pooler.supabase.com
      port: 5432
      user: postgres.vhbjaolzqxmoizgkelco
      pass: "Vitasta@1019"
      dbname: postgres
      schema: public
      threads: 1
  target: dev